### ISSUE TITLE
variable spelling mistake

### ISSUE THREAD

**Issue by PFC-developer** [node-a-team/terra-oracle#12]
https://github.com/node-a-team/terra-oracle/blob/672bff2b2b2c3beb8adf8a80c4388cb2d125a68b/oracle/tx.go#L112

hey guys.. looks like you have a typo

latestHeig<n>t instead of latestHeig<h>t

Cheers!

**Comment by wlsaud619** [comment]
Thanks! :)

**Comment by wlsaud619** [comment]
Fixed since `v0.0.5-alpha.8-a`
